version: '2'

services:
  klipper:
    # image: dimalo/klipper-moonraker
    build:
      dockerfile: ./klipper/Dockerfile
      context: .
    # if klipper cannot connect to the printer check permissions on rpi then add the group here
    group_add:
      - "20"
    #   - "998"
    cap_add:
      - SYS_NICE
    container_name: klipper
    ports:
      - 7125:7125
    restart: unless-stopped
    volumes:
      #- gcode_files:/home/klippy/gcode_files
      - /home/volumes/gcode_files:/home/klippy/printer_data/gcodes
      - /home/volumes/klipper-web/config:/home/klippy/printer_data/config
      - /home/volumes/moonraker_data:/home/klippy/printer_data
      # be aware to create your own branch if you mount the config folder as it will be updated on the main branch
      # that way you can merge upstream changes to your customized configs
      #- ./config:/home/klippy/.config
      #- moonraker_data:/home/klippy/.moonraker_database
      # - <<your_config_path>>:/home/klippy/.config
      # - ./printer.cfg:/home/klippy/.config/printer.cfg
    # mount serial device - take care to grant sufficient permissions to the device: <host_dev>:<container_dev>
    # put <container_dev> into your printer.cfg
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0

  fluidd:
    image: dimalo/fluidd
    build:
      dockerfile: Dockerfile
      context: frontend
    restart: unless-stopped
    container_name: fluidd
    ports:
      - 8010:80
    depends_on: 
      - klipper
    links:
      - klipper:klipper

